"""Password hashing policy shared by the authentication stacks."""

from argon2 import (
    DEFAULT_HASH_LENGTH,
    DEFAULT_MEMORY_COST,
    DEFAULT_PARALLELISM,
    DEFAULT_TIME_COST,
)

ARGON2_MEMORY_COST = DEFAULT_MEMORY_COST
ARGON2_TIME_COST = DEFAULT_TIME_COST
ARGON2_PARALLELISM = DEFAULT_PARALLELISM
ARGON2_HASH_LENGTH = DEFAULT_HASH_LENGTH
