"""Bounded contracts for organic-result content differentiation."""

from typing import Final

DIFFERENTIATION_FORMULA_VERSION: Final = "content-differentiation-1"
DIFFERENTIATION_RESULT_LIMIT: Final = 10
DIFFERENTIATION_MIN_INSPECTED_PAGES: Final = 3
DIFFERENTIATION_MIN_SOURCE_CHARS: Final = 200
DIFFERENTIATION_MOST_PAGES_RATIO: Final = 0.6
DIFFERENTIATION_MAX_OWNED_PAGE_CANDIDATES: Final = 1000
DIFFERENTIATION_MAX_FEATURE_VALUES: Final = 100
SOURCE_PAGE_MAX_TABLES: Final = 50
SOURCE_PAGE_MAX_TABLE_HEADERS: Final = 12
