/**
 * The route-ownership manifest: which stack writes each `/api/v1` route
 * family (TypeScript migration rule 1).
 *
 * A family is one OpenAPI tag. Exactly one stack serves it: the PR that moves
 * a family to TypeScript flips its entry and deletes the Python router. The route-ownership gate
 * (`frontend/services/api/scripts/check-route-ownership.ts`) holds both
 * stacks' OpenAPI documents and both ingress Caddyfiles to this record.
 */
export type RouteStack = 'python' | 'typescript';

export const ROUTE_OWNERSHIP = {
  actions: 'typescript',
  agent: 'python',
  'ai-referrals': 'typescript',
  'audit-schedules': 'typescript',
  audits: 'python',
  auth: 'typescript',
  billing: 'typescript',
  'billing-documents': 'typescript',
  'brand-identity': 'typescript',
  'brand-discoveries': 'typescript',
  commerce: 'typescript',
  'commerce-python': 'python',
  demand: 'typescript',
  executions: 'typescript',
  integrations: 'typescript',
  'mcp-connections': 'typescript',
  opportunities: 'typescript',
  performance: 'typescript',
  'performance-sync': 'typescript',
  readiness: 'python',
  projects: 'typescript',
  'executive-report': 'typescript',
  'prompt-generation': 'typescript',
  prompts: 'typescript',
  providers: 'typescript',
  'search-intelligence': 'typescript',
  'search-intelligence-reviews': 'python',
  'site-health': 'python',
  'site-health-internal-links': 'typescript',
  visibility: 'typescript',
  workspaces: 'typescript',
} as const satisfies Record<string, RouteStack>;

export type RouteFamily = keyof typeof ROUTE_OWNERSHIP;

/**
 * The ingress path patterns (Caddy `path` syntax, `*` within one segment)
 * that reach the TypeScript service. Every ingress Caddyfile names these
 * paths, which the route-ownership gate proves against both OpenAPI
 * documents; the development proxy reads this list directly.
 */
export const TYPESCRIPT_INGRESS_PATHS = [
  '/api/v1/provider-catalog',
  '/api/v1/provider-connections',
  '/api/v1/provider-connections/*',
  '/api/v1/billing/invoices',
  '/api/v1/billing/invoices/*/pdf',
  '/api/v1/projects/*/reports/executive.pdf',
  '/api/v1/mcp/connections',
  '/api/v1/mcp/connections/*',
  '/api/v1/workspaces/*/mcp/connections',
  '/api/v1/workspaces/*/mcp/connections/*',
  '/mcp',
  '/mcp/*',
  '/authorize',
  '/token',
  '/revoke',
  '/.well-known/oauth-authorization-server',
  '/.well-known/oauth-protected-resource/mcp',
  '/api/v1/billing/catalog',
  '/api/v1/billing/entitlement',
  '/api/v1/billing/usage',
  '/api/v1/billing/early-access',
  '/api/v1/billing/early-access/claim',
  '/api/v1/billing/card-trial/quote',
  '/api/v1/billing/subscriptions',
  '/api/v1/billing/subscription',
  '/api/v1/billing/subscription/change',
  '/api/v1/billing/addons',
  '/api/v1/billing/topups',
  '/api/v1/billing/activations/*',
  '/api/v1/billing/activations/*/checkout',
  '/api/v1/billing/activations/*/verify',
  '/api/v1/billing/webhooks/*',
  '/api/v1/workspaces/*/entitlements',
  '/api/v1/projects/*/audit-schedules',
  '/api/v1/projects/*/audit-schedules/*',
  '/api/v1/projects',
  '/api/v1/projects/*-*-*-*-*',
  '/api/v1/projects/*/logos/refresh',
  '/api/v1/projects/*/command-center',
  '/api/v1/brand-discovery-catalog',
  '/api/v1/brand-discoveries',
  '/api/v1/brand-discoveries/*',
  '/api/v1/integrations',
  '/api/v1/integrations/*',
  '/api/v1/auth/*',
  '/api/v1/workspaces',
  '/api/v1/workspaces/invitations/accept',
  '/api/v1/workspaces/*/members',
  '/api/v1/workspaces/*/members/*-*-*-*-*',
  '/api/v1/workspaces/*/members/leave',
  '/api/v1/workspaces/*/ownership',
  '/api/v1/workspaces/*/invitations',
  '/api/v1/workspaces/*/invitations/*-*-*-*-*',
  '/api/v1/workspaces/*/invitations/*/resend',
  '/api/v1/workspaces/*/policies',
  '/api/v1/workspaces/*/product-tour',
  '/api/v1/projects/*/site-health/internal-links',
  '/api/v1/projects/*/site-health/internal-links/*',
  '/api/v1/projects/*/site-health/internal-links/analyses/*/cancel',
  '/api/v1/projects/*/commerce/catalog',
  '/api/v1/projects/*/commerce/catalog/import',
  '/api/v1/projects/*/commerce/competitors',
  '/api/v1/projects/*/commerce/competitors/discoveries',
  '/api/v1/projects/*/commerce/competitors/*-*-*-*-*',
  '/api/v1/projects/*/commerce/buyer-prompts/generate',
  '/api/v1/projects/*/commerce/buyer-prompts/manual',
  '/api/v1/projects/*/commerce/buyer-prompts',
  '/api/v1/projects/*/commerce/buyer-prompts/*-*-*-*-*',
  '/api/v1/projects/*/commerce/ai-shelf',
  '/api/v1/projects/*/brand-profile',
  '/api/v1/projects/*/business-map',
  '/api/v1/projects/*/competitor-suggestions',
  '/api/v1/projects/*/competitor-suggestions/*/accept',
  '/api/v1/projects/*/logo',
  '/api/v1/projects/*/topics',
  '/api/v1/topics/*',
  '/api/v1/prompt-sets',
  '/api/v1/prompt-sets/*-*-*-*-*',
  '/api/v1/prompt-sets/*/generate',
  '/api/v1/prompt-sets/*/prompts',
  '/api/v1/prompt-sets/*/prompts/bulk-status',
  '/api/v1/prompt-sets/*/import',
  '/api/v1/prompt-sets/*/candidates',
  '/api/v1/prompt-sets/*/candidates/review',
  '/api/v1/prompts/*',
  '/api/v1/projects/*/competitors/*/logo',
  '/api/v1/executions/*',
  '/api/v1/projects/*/ai-referrals',
  '/api/v1/projects/*/performance',
  '/api/v1/projects/*/performance/table',
  '/api/v1/projects/*/performance/range',
  '/api/v1/projects/*/performance/range/*',
  '/api/v1/projects/*/performance/sync',
  '/api/v1/projects/*/demand/*',
  '/api/v1/projects/*/demand/query-evidence/summary',
  '/api/v1/projects/*/visibility',
  '/api/v1/projects/*/visibility/*',
  '/api/v1/projects/*/visibility/sources/*',
  '/api/v1/projects/*/opportunities',
  '/api/v1/projects/*/opportunities/*',
  '/api/v1/opportunities/*',
  '/api/v1/projects/*/actions',
  '/api/v1/actions/*',
  '/api/v1/projects/*/search-intelligence',
  '/api/v1/projects/*/search-intelligence/preferences',
  '/api/v1/projects/*/search-intelligence/runs',
  '/api/v1/projects/*/search-intelligence/runs/*',
  '/api/v1/projects/*/search-intelligence/runs/*/confirm',
  '/api/v1/projects/*/search-intelligence/runs/*/cancel',
  '/api/v1/projects/*/search-intelligence/datasets/*/rows',
  '/api/v1/projects/*/search-intelligence/content-handoff',
  '/api/v1/projects/*/search-intelligence/citation-matches',
] as const;
