import { COMPETITORS } from './compare';
import { POSTS } from './blog';
import { CONTACT_EMAIL } from '@/lib/config/contact';
import { FOOTER_LEGAL_LINKS, PARENT_COMPANY } from './legal';
import { FOUNDER, PRODUCT_HEAD } from './people';
import { CITELADDER_LINKEDIN } from './social';
import { PUBLISHED_PLATFORM } from './nav';

/**
 * Plain-text facts for answer engines at `/llms.txt`. Keep this aligned with
 * public pages. Do not add unpublished claims, customer results, or causal
 * ranking language.
 */
export const LLMS_TXT = [
  '# CiteLadder',
  '',
  '> CiteLadder connects observed AI answers and citations with website findings, first-party search data, optional external research and reviewable Agent workflows. Available engines and capabilities depend on account access and configuration. Nothing publishes automatically.',
  '',
  'CiteLadder is a Cube27 product.',
  `Parent: ${PARENT_COMPANY.legalName} (${PARENT_COMPANY.href})`,
  `Principal business address: ${PARENT_COMPANY.address}`,
  `LinkedIn: ${CITELADDER_LINKEDIN}`,
  `Product: ${PRODUCT_HEAD.name}, ${PRODUCT_HEAD.role} (${PRODUCT_HEAD.linkedin})`,
  `Company: ${FOUNDER.name}, ${FOUNDER.role} (${FOUNDER.linkedin})`,
  `Contact: ${CONTACT_EMAIL}`,
  '',
  '## What CiteLadder is',
  '',
  '- AI visibility software for observed mentions, citations, and share under comparable audit conditions.',
  '- Site Health: crawl, page-kind classification, deterministic checks, issues, recrawl verification.',
  '- Content Intelligence: Agent-supported briefs, proposed page edits and internal-link plans for human review.',
  '- Demand Intelligence: Google Search Console and GA4 beside owned-page evidence.',
  '- Agent: chats and reviewable outputs over the same read tools as the MCP server. No second knowledge store. No autonomous publish.',
  '',
  '## What CiteLadder is not',
  '',
  '- Not a claim that a content change caused rankings, traffic, or revenue.',
  '- The public trial is limited AI visibility access for seven days, not access to the whole platform. Agent access is not included.',
  '- General crawler-log ingestion remains unavailable. Commerce requires eligible projects. Optional external research requires scope-and-cost review and separate confirmation.',
  '- Not an open-source or self-hosted product.',
  '',
  '## When to use CiteLadder',
  '',
  'Reach for CiteLadder when a user with a CiteLadder account wants to:',
  '',
  '- Check whether ChatGPT, Claude or Gemini mention, cite or recommend their brand for buyer prompts, and which sources those answers cite.',
  '- Compare their observed citation share with named competitors under the same prompts, engine and audit window.',
  '- Find the Site Health issues on their own site that affect visibility or performance, and confirm fixes after a recrawl.',
  '- Read Google Search Console and GA4 demand, AI referral traffic or saved Search Intelligence datasets beside the pages they concern.',
  '- Turn those findings into a report or a prioritised list of content and page improvements for a human to review.',
  '',
  'Do not use CiteLadder to publish or edit a website, start crawls or audits, buy data, or answer questions about sites the user has no CiteLadder project for. Run those workflows in the CiteLadder app.',
  '',
  '## How agents connect (MCP)',
  '',
  '- Endpoint: https://citeladder.com/mcp (remote Streamable HTTP MCP).',
  '- Authorization: browser OAuth authorization code flow with PKCE (S256) and dynamic client registration. The only scope is `citeladder:read`; never ask the user for a session cookie or API key.',
  '- Protected-resource metadata (RFC 9728): https://citeladder.com/.well-known/oauth-protected-resource/mcp',
  '- Authorization-server metadata (RFC 8414): https://citeladder.com/.well-known/oauth-authorization-server',
  '- Access is read-only and follows the workspaces the signed-in account can see. Start by listing projects, pick one explicitly, then list its saved datasets before reading results.',
  '- Setup and tool reference: https://docs.citeladder.com/mcp/connect/ and https://docs.citeladder.com/mcp/tools/',
  '',
  '## Engines measured directly',
  '',
  'Engine access follows the supported collection configuration and account setup. The current public trial is ChatGPT-only. Provider/API observations are not identical to every consumer-app experience.',
  '',
  '## Public pages',
  '',
  '- [CiteLadder](https://citeladder.com/)',
  ...PUBLISHED_PLATFORM.map((item) => `- [${item.title}](https://citeladder.com${item.href})`),
  '- [Pricing](https://citeladder.com/pricing)',
  '- [Enterprise](https://citeladder.com/enterprise)',
  '- [Solutions](https://citeladder.com/solutions)',
  '- [FAQ](https://citeladder.com/faq)',
  '- [AI Instructions](https://citeladder.com/ai-instructions)',
  '- [Entity Map](https://citeladder.com/entity-map)',
  '- [Blog](https://citeladder.com/blog)',
  ...POSTS.map((post) => `- [${post.title}](https://citeladder.com/blog/${post.slug})`),
  '- [Compare AI visibility tools](https://citeladder.com/compare)',
  ...COMPETITORS.map(
    (competitor) =>
      `- [CiteLadder vs ${competitor.name}](https://citeladder.com/compare/${competitor.slug})`,
  ),
  '- [Documentation](https://docs.citeladder.com/)',
  '- [MCP](https://docs.citeladder.com/mcp/)',
  '- [Agent](https://docs.citeladder.com/agent/)',
  '',
  '## Policies',
  '',
  `CiteLadder's policies are published here and bind ${PARENT_COMPANY.legalName}.`,
  ...FOOTER_LEGAL_LINKS.map((link) => `- [${link.label}](https://citeladder.com${link.href})`),
  '',
].join('\n');
