export {};
type Fetcher = { fetch(request: Request): Promise<Response> };
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/marketing/wrangler.jsonc --include-runtime=false apps/marketing/worker-configuration.d.ts` (hash: b634ec13a7f3b1ad83048d968514f578)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
  ORIGIN_UPSTREAM: 'https://citeladder-api-44437656491.us-central1.run.app';
  PUBLIC_WEBSITE_HOST: 'citeladder.com';
  PUBLIC_APP_ORIGIN: 'https://app.citeladder.com';
  ORIGIN_TOKEN: string;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};

export type WorkerEnv = Env;
