export {};
type Fetcher = { fetch(request: Request): Promise<Response> };
type RateLimit = { limit(input: { key: string }): Promise<{ success: boolean }> };

/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/marketing/wrangler.jsonc --include-runtime=false apps/marketing/worker-configuration.d.ts` (hash: ec394912b5ae6e2b9d668ba0d3ce7b48)
interface __BaseEnv_Env {
  CONTACT_IP_LIMITER: RateLimit;
  CONTACT_BURST_LIMITER: RateLimit;
  ASSETS: Fetcher;
  ORIGIN_UPSTREAM: 'https://citeladder-api-44437656491.us-central1.run.app';
  PUBLIC_WEBSITE_HOST: 'citeladder.com';
  PUBLIC_APP_ORIGIN: 'https://app.citeladder.com';
  TURNSTILE_HOSTNAMES: 'citeladder.com';
  ORIGIN_TOKEN: string;
  RESEND_API_KEY: string;
  TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};

export type WorkerEnv = Env;
