/** Downloadable standalone Worker generated from the catalog and shared matcher. */
import { writeTemplate } from './template-file.ts';
import { crawlers, matchesCrawlerUserAgent } from '../src/config/crawlers.ts';
import { crawlLogs } from '../src/config/crawl-logs.ts';
const prefix = '// Generated by services/api/scripts/export-crawl-worker.ts. Do not edit.\n';
const catalog =
  'const bots = ' +
  JSON.stringify(
    // Robots-only tokens have no user agent to match.
    crawlers.bots.filter((b) => b.ua_patterns.length).map((b) => ({ ua_patterns: b.ua_patterns })),
    null,
    2,
  ) +
  ';\n';
const matcher = matchesCrawlerUserAgent.toString() + '\n';
const worker = String.raw`
// Recognized requests are buffered per isolate and sent as one NDJSON batch when the
// oldest has waited ${crawlLogs.worker_flush_seconds} s or ${crawlLogs.worker_batch_lines} are pending. Best effort: a buffer
// is lost if Cloudflare evicts the isolate first, so coverage is never complete.
const pending = [];
let oldestPendingAt = 0;
function deliver(env, lines) {
  return fetch(env.CITELADDER_INGEST_URL, {
    method: 'POST',
    headers: { 'Authorization': 'Bearer ' + env.CITELADDER_CRAWL_TOKEN, 'Content-Type': 'application/x-ndjson' },
    body: lines.join('\n'),
    signal: AbortSignal.timeout(${crawlLogs.worker_timeout_ms})
  }).then(result => {
    if (!result.ok) console.error('CiteLadder crawl log delivery failed', result.status);
  }, () => console.error('CiteLadder crawl log delivery failed'));
}
const worker = {
  async fetch(request, env, ctx) {
    const response = await fetch(request);
    const userAgent = request.headers.get('user-agent') || '';
    if (bots.some(bot => matchesCrawlerUserAgent(bot, userAgent))) {
      const url = new URL(request.url);
      if (!pending.length) oldestPendingAt = Date.now();
      pending.push(JSON.stringify({
        timestamp: new Date().toISOString(), host: url.hostname, path: url.pathname,
        method: request.method, status: response.status, user_agent: userAgent,
        client_ip: request.headers.get('cf-connecting-ip'),
        request_id: request.headers.get('cf-ray')?.split('-')[0] ?? null
      }));
    }
    if (pending.length && (pending.length >= ${crawlLogs.worker_batch_lines} || Date.now() - oldestPendingAt >= ${crawlLogs.worker_flush_seconds * 1000}))
      ctx.waitUntil(deliver(env, pending.splice(0)));
    return response;
  }
};
export default worker;
`;
await writeTemplate(
  'citeladder-crawl-log-worker.js',
  prefix + catalog + matcher + worker,
  'crawl:worker',
);
