/** Downloadable standalone Worker generated from the catalog and shared matcher. */
import { mkdir, writeFile } from 'node:fs/promises';
import { crawlers, matchesCrawlerUserAgent } from '../src/config/crawlers.ts';
import { crawlLogs } from '../src/config/crawl-logs.ts';
const prefix = '// Generated by services/api/scripts/export-crawl-worker.ts. Do not edit.\n';
const catalog =
  'const bots = ' +
  JSON.stringify(
    crawlers.bots.map((b) => ({ ua_patterns: b.ua_patterns })),
    null,
    2,
  ) +
  ';\n';
const matcher = matchesCrawlerUserAgent.toString() + '\n';
const worker = `
const worker = {
  async fetch(request, env, ctx) {
    const response = await fetch(request);
    const userAgent = request.headers.get('user-agent') || '';
    if (bots.some(bot => matchesCrawlerUserAgent(bot, userAgent))) {
      const url = new URL(request.url);
      const event = {
        timestamp: new Date().toISOString(), host: url.hostname, path: url.pathname,
        method: request.method, status: response.status, user_agent: userAgent,
        client_ip: request.headers.get('cf-connecting-ip'),
        request_id: request.headers.get('cf-ray')?.split('-')[0] ?? null
      };
      // One best-effort send per recognized request; no batching or durability.
      ctx.waitUntil(Promise.resolve().then(async () => {
        try {
          const result = await fetch(env.CITELADDER_INGEST_URL, {
            method: 'POST',
            headers: { 'Authorization': 'Bearer ' + env.CITELADDER_CRAWL_TOKEN, 'Content-Type': 'application/x-ndjson' },
            body: JSON.stringify(event),
            signal: AbortSignal.timeout(${crawlLogs.worker_timeout_ms})
          });
          if (!result.ok) console.error('CiteLadder crawl log delivery failed', result.status);
        } catch {
          console.error('CiteLadder crawl log delivery failed');
        }
      }));
    }
    return response;
  }
};
export default worker;
`;
await mkdir(new URL('../../../apps/docs/public/templates/', import.meta.url), { recursive: true });
await writeFile(
  new URL('../../../apps/docs/public/templates/citeladder-crawl-log-worker.js', import.meta.url),
  prefix + catalog + matcher + worker,
);
