/** Source of the optional Firehose transformation Lambda that keeps recognized crawler records. */
import { matchesCrawlerUserAgent } from '../src/config/crawlers.ts';

type Catalog = {
  catalog_version: string;
  bots: readonly { ua_patterns: readonly string[] }[];
};

export function firehoseFilterSource(catalog: Catalog): string {
  const bots = JSON.stringify(
    // Robots-only tokens have no user agent to match.
    catalog.bots.filter((b) => b.ua_patterns.length).map((b) => ({ ua_patterns: b.ua_patterns })),
    null,
    2,
  );
  return String.raw`// Generated by services/api/scripts/export-firehose-filter.ts. Do not edit.
// Amazon Data Firehose transformation Lambda (Node.js runtime) for CloudFront
// standard logs (JSON): keeps a record's log lines whose cs(User-Agent) belongs to a
// recognized crawler and drops the record when none does. A stream running it is
// filtered, so CiteLadder reports its coverage as partial.
export const CATALOG_VERSION = ${JSON.stringify(catalog.catalog_version)};
const bots = ${bots};
${matchesCrawlerUserAgent.toString()}
function userAgent(line) {
  try {
    const value = JSON.parse(line)['cs(User-Agent)'];
    if (typeof value !== 'string') return '';
    try {
      return decodeURIComponent(value);
    } catch {
      return value;
    }
  } catch {
    return '';
  }
}
export const handler = async (event) => ({
  records: event.records.map((record) => {
    const lines = Buffer.from(record.data, 'base64')
      .toString('utf8')
      .split('\n')
      .filter((line) => line.trim());
    const kept = lines.filter((line) => bots.some((bot) => matchesCrawlerUserAgent(bot, userAgent(line))));
    if (!kept.length) return { recordId: record.recordId, result: 'Dropped', data: record.data };
    return {
      recordId: record.recordId,
      result: 'Ok',
      data: Buffer.from(kept.join('\n') + '\n').toString('base64'),
    };
  }),
});
`;
}
