export {};
type Fetcher = { fetch(request: Request): Promise<Response> };
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/app/wrangler.jsonc --include-runtime=false apps/app/worker-configuration.d.ts` (hash: 40cdd4d0e23b8ae08f6900802b55155a)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
  ORIGIN_UPSTREAM: 'https://staging-origin.citeladder.com' | 'https://origin.citeladder.com';
  PUBLIC_APP_HOST: 'staging-app.citeladder.com' | 'app.citeladder.com';
  ORIGIN_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
  }
  interface StagingEnv {
    ASSETS: Fetcher;
    ORIGIN_UPSTREAM: 'https://staging-origin.citeladder.com';
    PUBLIC_APP_HOST: 'staging-app.citeladder.com';
    ORIGIN_TOKEN: string;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};

export type WorkerEnv = Env;
