export {};
type Fetcher = { fetch(request: Request): Promise<Response> };
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/app/wrangler.jsonc --include-runtime=false apps/app/worker-configuration.d.ts` (hash: cd4865f99771aa4a18a85f02627d7110)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
  ORIGIN_UPSTREAM: 'https://origin.citeladder.com';
  PUBLIC_APP_HOST: 'app.citeladder.com';
  ORIGIN_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};

export type WorkerEnv = Env;
