import type { ReactNode } from 'react';

import { cn } from '@/lib/utils';

import { Eyebrow } from './label';
import { Reveal } from './reveal';

// The public editorial ladder resolves these semantic rungs responsively;
// embedded product previews reset to the compact app ladder.
const SECTION_HEADING_CLASSES = {
  h1: 'website-page-title',
  h2: 'website-section-heading',
  h3: 'website-feature-heading',
} as const;

/**
 * Vertical rhythm for the whole public surface. Sections NEVER set their own
 * padding — the six cases live here, so every page breathes identically
 * (docs/design.md §3).
 *
 * The ladder is one token, `--section-y` (96 desktop / 80 tablet / 56 mobile),
 * so the rhythm steps with the viewport in one place instead of three literal
 * breakpoint values per variant. `tight` is the step below `base`, for bands
 * that read as one block with their neighbour.
 *
 * There were four more variants — `hero`, `open`, `close`, `none` — and none
 * had a call site. `open`/`close` were the manual answer to a run of same-tone
 * sections, which the `[data-citeladder-section]` seam rule in globals.css now
 * handles on its own.
 */
const RHYTHM = {
  base: 'py-[var(--section-y)]',
  tight: 'py-[calc(var(--section-y)*0.65)]',
} as const;

type Rhythm = keyof typeof RHYTHM;

/**
 * Band fills. On the paper canvas a tonal band is a whisper, so most sections
 * separate with `divided` (a hairline) instead — a rule reads at any size, a
 * two-percent fill difference does not. Only two fills exist by design: the
 * paper canvas and one recessed tone. A section background is never a new hue,
 * and never a gradient (§1).
 */
const TONE = {
  paper: '',
  sunken: 'bg-background-alt',
} as const;

type Tone = keyof typeof TONE;

type SectionProps = Readonly<{
  children: ReactNode;
  rhythm?: Rhythm;
  tone?: Tone;
  /** Hairline rule above the section — only for same-tone adjacency. */
  divided?: boolean;
  /** Full-bleed: skips the container so the child owns its width. */
  bleed?: boolean;
  /** Dense single-block sections drop the 50px container gap to 10px. */
  dense?: boolean;
  id?: string;
  className?: string;
  'aria-label'?: string;
  'aria-labelledby'?: string;
}>;

export function Section({
  children,
  rhythm = 'base',
  tone = 'paper',
  divided = false,
  bleed = false,
  dense = false,
  id,
  className,
  ...aria
}: SectionProps) {
  return (
    <section
      id={id}
      // Two same-tone neighbours stack bottom + top padding and open a gap
      // twice the intended rhythm, which reads as a hole in the page rather
      // than a section break. `data-citeladder-section` lets globals.css collapse
      // the seam; a tone change keeps the full pair, because there the fill edge
      // is the boundary and needs the room.
      data-citeladder-section={tone}
      className={cn(
        'relative w-full',
        TONE[tone],
        RHYTHM[rhythm],
        divided && 'border-border-subtle border-t',
        className,
      )}
      {...aria}
    >
      {bleed ? children : <Container dense={dense}>{children}</Container>}
    </section>
  );
}

/**
 * The container is non-negotiable: 1280px max-width, centered, and the
 * `--site-gutter` step (40/32/20px) either side. The gutter is a token because
 * the classes that used to sit here — `px-6-phone` / `md:px-6-tablet` — were
 * never generated by Tailwind, which left every public page flush to the
 * viewport edge below `xl`.
 *
 * Sections stay full-bleed so backgrounds and decorative elements can run edge
 * to edge, and every piece of content sits in here.
 */
export function Container({
  children,
  dense = false,
  className,
}: Readonly<{ children: ReactNode; dense?: boolean; className?: string }>) {
  return (
    <div
      className={cn(
        'relative z-1 mx-auto flex w-full max-w-7xl flex-col px-[var(--site-gutter)]',
        dense ? 'gap-3' : 'gap-6 md:gap-8',
        className,
      )}
    >
      {children}
    </div>
  );
}

/**
 * The section heading group: eyebrow → heading → lead, at the 10–20px internal
 * gap the spec sets for a heading group (§3). Every section head goes through
 * this component — that is what keeps eyebrow distance and heading size from
 * drifting page by page.
 *
 * Entrance delays follow the spec's 0.1s sequence (eyebrow/heading 0.1s, lead
 * 0.2s), applied by `Reveal` on the group rather than per element.
 */
export function SectionHeader({
  eyebrow,
  title,
  lead,
  size = 'h2',
  headingId,
  as: Heading = 'h2',
  className,
}: Readonly<{
  eyebrow?: ReactNode;
  title: ReactNode;
  lead?: ReactNode;
  /** `h2` is the section default; `h3` is the compact rung for dense bands. */
  size?: 'h1' | 'h2' | 'h3';
  headingId?: string;
  as?: 'h1' | 'h2' | 'h3';
  className?: string;
}>) {
  return (
    <Reveal className={cn('flex flex-col gap-3', className)}>
      {eyebrow && <Eyebrow>{eyebrow}</Eyebrow>}
      <Heading
        id={headingId}
        className={cn('text-foreground max-w-[32ch] text-balance', SECTION_HEADING_CLASSES[size])}
      >
        {title}
      </Heading>
      {lead && <p className="website-lead text-muted max-w-[65ch]">{lead}</p>}
    </Reveal>
  );
}
