/** Actions catalog: deterministic decisions over persisted evidence. */
import { opportunities } from './opportunity.ts';

export const actions = {
  ACTION_STATUS_OPEN: 'open',
  ACTION_GROUPING_VERSION: 'action-grouping-2',
  ACTION_DIAGNOSIS_VERSION: 'action-diagnosis-2',
  ACTION_PRIORITY_VERSION: 'action-priority-1',
  TARGET_PAGE: 'page',
  TARGET_EARNED_PAGE: 'earned_page',
  TARGET_PRODUCT: 'product',
  TARGET_CATEGORY: 'category',
  TARGET_QUERY: 'query',
  TARGET_PROMPT: 'prompt',
  TARGET_PLANNED_PAGE: 'planned_page',
  ACTION_TARGET_KINDS: [
    'page',
    'earned_page',
    'product',
    'category',
    'query',
    'prompt',
    'planned_page',
  ],
  AGENT_TARGET_KINDS: ['page', 'planned_page'],
  PLANNED_PAGE_TOPIC_MAX_CHARS: 120,
  ACTION_ORIGIN_EVIDENCE: 'evidence',
  ACTION_ORIGIN_AGENT: 'agent',
  ACTION_STATUS_IN_PROGRESS: 'in_progress',
  ACTION_STATUS_IMPLEMENTED: 'implemented',
  ACTION_STATUS_MEASURING: 'measuring',
  ACTION_STATUS_DONE: 'done',
  ACTION_STATUSES: ['open', 'in_progress', 'implemented', 'measuring', 'done', 'dismissed'],
  ACTION_USER_STATUSES: ['dismissed', 'open'],
  ACTION_ACTIVE_STATUSES: ['in_progress', 'open'],
  FAMILY_AI_VISIBILITY: 'ai_visibility',
  FAMILY_SOURCES: 'sources',
  FAMILY_SEARCH_CONSOLE: 'search_console',
  FAMILY_SITE_HEALTH: 'site_health',
  FAMILY_LINK_GRAPH: 'link_graph',
  FAMILY_SITE_CHANGES: 'site_changes',
  FAMILY_COMMERCE: 'commerce',
  FAMILY_SEARCH_INTELLIGENCE: 'search_intelligence',
  EVIDENCE_FAMILIES: [
    'ai_visibility',
    'sources',
    'search_console',
    'search_intelligence',
    'site_health',
    'link_graph',
    'site_changes',
    'commerce',
  ],
  RULE_EVIDENCE_FAMILY: {
    brand_absent_high_value_prompt: 'ai_visibility',
    owned_page_not_cited: 'ai_visibility',
    confirmed_prompt_decline: 'ai_visibility',
    earned_page_acquire_listing: 'sources',
    missing_structured_data: 'site_health',
    schema_properties_incomplete: 'site_health',
    schema_visible_content_conflict: 'site_health',
    content_structure_incomplete: 'site_health',
    citability_trust_incomplete: 'site_health',
    site_link_near_orphan: 'link_graph',
    site_contextual_links: 'link_graph',
    site_link_weak_authority: 'link_graph',
    site_change_potential_regression: 'site_changes',
    site_change_critical_regression: 'site_changes',
    site_change_metadata_inconsistency: 'site_changes',
    site_change_cosmetic_refresh: 'site_changes',
    search_demand_content_gap: 'search_console',
    striking_distance_query: 'search_console',
    query_cannibalization: 'search_console',
    property_relative_ctr_gap: 'search_console',
    emerging_query: 'search_console',
    declining_query: 'search_console',
    search_keyword_gap: 'search_intelligence',
    low_share_of_voice_theme: 'ai_visibility',
    high_traffic_low_visibility: 'search_console',
    product_not_mentioned: 'commerce',
    cited_alternatives_without_uploaded_presence: 'commerce',
    catalog_fields_missing: 'commerce',
  },
  CONVERGENCE_BONUS_PER_FAMILY: 0.15,
  CONVERGENCE_MULTIPLIER_CAP: 1.6,
  ACTION_PRIORITY_ROUNDING_DECIMALS: 1,
  APPROACH_TREE: [
    {
      approach: 'earned_placement',
      rule_ids: ['earned_page_acquire_listing'],
      skill_id: 'earned_authority',
      donts: [
        'Do not change an owned page to fix a third-party listing.',
        'Do not send outreach from CiteLadder; drafts only.',
      ],
      target_kinds: [],
    },
    {
      approach: 'fix_technical',
      rule_ids: [
        'missing_structured_data',
        'schema_properties_incomplete',
        'schema_visible_content_conflict',
        'site_change_critical_regression',
        'site_change_potential_regression',
      ],
      skill_id: 'technical_health',
      donts: [
        'Do not rewrite the page copy to work around a technical defect.',
        'Do not add markup that states facts the visible page does not.',
      ],
      target_kinds: [],
    },
    {
      approach: 'consolidate',
      rule_ids: ['query_cannibalization'],
      skill_id: 'gsc_optimize',
      donts: ['Do not create another URL for this demand.'],
      target_kinds: [],
    },
    {
      approach: 'create_new',
      rule_ids: ['brand_absent_high_value_prompt'],
      skill_id: 'content_create',
      donts: [
        'Do not create a new URL if an existing page already answers this question; improve that page instead.',
      ],
      target_kinds: ['prompt'],
    },
    {
      approach: 'create_new',
      rule_ids: ['search_keyword_gap'],
      skill_id: 'content_create',
      donts: [
        'Do not create a new URL if an existing page already answers this search; improve that page instead.',
        'Do not present provider ranking estimates as measured traffic.',
      ],
      target_kinds: ['planned_page'],
    },
    {
      approach: 'improve_links',
      rule_ids: ['site_contextual_links', 'site_link_near_orphan', 'site_link_weak_authority'],
      skill_id: 'internal_links',
      donts: ['Do not add links from unrelated pages to hit a link count.'],
      target_kinds: [],
    },
    {
      approach: 'improve_existing',
      rule_ids: [
        'declining_query',
        'emerging_query',
        'property_relative_ctr_gap',
        'search_demand_content_gap',
        'striking_distance_query',
      ],
      skill_id: 'gsc_optimize',
      donts: ['Do not create another URL: an indexable page already maps to this demand.'],
      target_kinds: [],
    },
  ],
  DEFAULT_APPROACH: {
    approach: 'improve_existing',
    rule_ids: [],
    skill_id: 'content_create',
    donts: ['Do not create another URL for a target that already has a page.'],
    target_kinds: [],
  },
  AGENT_ORIGIN_DEFAULT_SKILL: 'content_create',
  LEG_VISIBILITY_RUN: 'next_visibility_run',
  LEG_SEARCH_CONSOLE_WINDOW: 'next_search_console_window',
  LEG_CRAWL: 'next_crawl',
  FAMILY_MEASUREMENT_LEG: {
    ai_visibility: 'next_visibility_run',
    // An earned listing is measured on the prompts that cite the page.
    sources: 'next_visibility_run',
    search_console: 'next_search_console_window',
    // A later paid analysis may also read it, but the scheduled reading is Search Console.
    search_intelligence: 'next_search_console_window',
    site_health: 'next_crawl',
    link_graph: 'next_crawl',
    site_changes: 'next_crawl',
    commerce: 'next_visibility_run',
  },
  CHECK_KIND_MEASUREMENT_LEG: {
    site_rule: 'next_crawl',
    contextual_link: 'next_crawl',
    visibility_metric: 'next_visibility_run',
    traffic_metric: 'next_search_console_window',
    keyword_presence: 'next_search_console_window',
  },
  LEG_STATE_WAITING: 'waiting',
  LEG_STATE_NOT_SCHEDULED: 'not_scheduled',
  LEG_STATE_SYNC_NEEDED: 'sync_needed',
  LEG_STATE_OBSERVED: 'observed',
  SEARCH_CONSOLE_FINALIZATION_LAG_DAYS: 3,
  FAMILY_STATE_OBSERVED: 'observed',
  FAMILY_STATE_NO_FINDING: 'no_finding',
  FAMILY_STATE_UNAVAILABLE: 'unavailable',
  ACTION_LIST_DEFAULT_LIMIT: 50,
  ACTION_LIST_MAX_LIMIT: 200,
  ACTION_LABEL_MAX_CHARS: 255,
};

// Every detector must participate in convergence and diagnosis.
const unmappedRules = Object.keys(opportunities.OPPORTUNITY_RULES_BY_ID).filter(
  (rule) => !Object.hasOwn(actions.RULE_EVIDENCE_FAMILY, rule),
);
if (unmappedRules.length)
  throw new Error(`Rules without an evidence family: ${unmappedRules.join(', ')}`);
