/** Launch authoring policy; persisted revisions remain the commercial authority. */
export const catalogAuthoring = {
  revision: 'launch-pricing-v1',
  usdInrRate: '90',
  expiryDays: 30,
  quantityMax: 20,
  maximumInputBytes: 1_048_576,
  contactUrl: 'https://www.cube27.com/contact/',
  supportEmail: 'contact@cube27.com',
  plans: [
    {
      key: 'tier_1',
      name: 'Starter',
      description: 'Daily AI visibility tracking for one project.',
      byok: 4900,
      funded: 9900,
      projects: 1,
      prompts: 10,
      urls: 50,
      fetches: 500,
      history: '90d',
      runs: 3,
      credits: 0,
      upper: false,
      support: 'standard',
    },
    {
      key: 'tier_2',
      name: 'Growth',
      description: 'Prompt fan-out and the Agent for three projects.',
      byok: 9900,
      funded: 24900,
      projects: 3,
      prompts: 30,
      urls: 150,
      fetches: 1500,
      history: '12mo',
      runs: 6,
      credits: 500,
      upper: true,
      support: 'standard',
    },
    {
      key: 'tier_3',
      name: 'Scale',
      description: 'Ten projects, two years of history and priority support.',
      byok: 19900,
      funded: 49900,
      projects: 10,
      prompts: 60,
      urls: 400,
      fetches: 4000,
      history: '24mo',
      runs: 12,
      credits: 1500,
      upper: true,
      support: 'priority',
    },
  ],
  items: [
    {
      key: 'addon_extra_project',
      name: 'Extra project',
      description: 'One more tracked project for 30 days.',
      available: true,
      byok: 1900,
      funded: 1900,
      grants: [{ key: 'project_slots', value: 1 }],
      fundedGrants: null,
      upperOnly: false,
      topup: false,
    },
    {
      key: 'addon_extra_prompts',
      name: 'Extra 10 prompts',
      description: 'Ten more tracked prompts for 30 days.',
      available: true,
      byok: 1500,
      funded: 9900,
      grants: [{ key: 'prompt_slots', value: 10 }],
      fundedGrants: [
        { key: 'prompt_slots', value: 10 },
        { key: 'audit_credits', value: 1000 },
      ],
      upperOnly: false,
      topup: false,
    },
    {
      key: 'addon_extra_site_health',
      name: 'Site Health pack',
      description: '250 more monitored URLs and 2,500 page fetches for 30 days.',
      available: true,
      byok: 1900,
      funded: 1900,
      grants: [
        { key: 'monitored_urls', value: 250 },
        { key: 'site_health_page_fetches_per_period', value: 2500 },
      ],
      fundedGrants: null,
      upperOnly: false,
      topup: false,
    },
    {
      key: 'topup_audit_credits',
      name: 'Managed answer top-up',
      description: '1,000 managed visibility answers, usable for 30 days.',
      available: false,
      byok: 9900,
      funded: 9900,
      grants: [{ key: 'audit_credits', value: 1000 }],
      fundedGrants: null,
      upperOnly: false,
      topup: true,
    },
    {
      key: 'topup_ai_credits',
      name: 'Workflow AI top-up',
      description: '1,000 AI credits for the Agent, 30 days.',
      available: true,
      byok: 2500,
      funded: 2500,
      grants: [{ key: 'ai_credits', value: 1000 }],
      fundedGrants: null,
      upperOnly: true,
      topup: true,
    },
  ],
} as const;
