/** Brand acquisition bounds and vocabulary, owned by the TypeScript runtime. */
export const brandEvidence = {
  request_timeout_seconds: 5,
  total_timeout_seconds: 12,
  max_redirects: 3,
  max_html_bytes: 2097152,
  max_pages: 5,
  max_navigation_links: 400,
  fallback_paths: ['/about', '/about-us', '/products', '/services', '/pricing'],
  offering_hub_terms: [
    'capabilities',
    'capability',
    'catalog',
    'catalogue',
    'categories',
    'category',
    'centers',
    'centres',
    'collection',
    'collections',
    'courses',
    'departments',
    'disciplines',
    'expertise',
    'industries',
    'offerings',
    'platform',
    'practice',
    'practices',
    'pricing',
    'products',
    'programmes',
    'programs',
    'sectors',
    'services',
    'shop',
    'solutions',
    'specialities',
    'specialties',
    'store',
    'treatments',
    'usecases',
    'whatwedo',
  ],
  editorial_link_terms: ['article', 'blog', 'guide', 'insights', 'journal', 'news', 'resources'],
  utility_link_terms: [
    'about',
    'accessibility',
    'account',
    'alumni',
    'annualreport',
    'awards',
    'basket',
    'board',
    'careers',
    'cart',
    'checkout',
    'complaints',
    'contact',
    'corporate',
    'csr',
    'dividend',
    'esg',
    'governance',
    'help',
    'investor',
    'investors',
    'leadership',
    'legal',
    'login',
    'logout',
    'milestones',
    'orders',
    'press',
    'privacy',
    'register',
    'shareholding',
    'signin',
    'signup',
    'sustainability',
    'terms',
    'wishlist',
  ],
  junk_label_terms: ['banner', 'icon', 'image', 'img', 'logo', 'thumbnail'],
  locale_labels: [
    'dansk',
    'deutsch',
    'english',
    'espanol',
    'español',
    'francais',
    'français',
    'italiano',
    'nederlands',
    'norsk',
    'polski',
    'portugues',
    'português',
    'suomi',
    'svenska',
    'turkce',
    'türkçe',
    'русский',
    'العربية',
    'हिन्दी',
    '中文',
    '日本語',
    '简体中文',
    '繁體中文',
    '한국어',
  ],
  max_nodes_per_label_family: 3,
  navigation_verbs: [
    'all',
    'apply now',
    'book now',
    'browse',
    'explore',
    'get started',
    'home',
    'learn more',
    'menu',
    'more',
    'new',
    'offers',
    'overview',
    'read more',
    'sale',
    'search',
    'see all',
    'shop now',
    'sign up',
    'start now',
    'view all',
  ],
  max_offering_nodes: 60,
  max_nodes_per_prefix: 8,
  max_nodes_per_page: 25,
  offering_label_max_words: 6,
  offering_label_min_chars: 3,
  offering_max_path_depth: 3,
  min_offering_nodes: 3,
  detail_path_pattern:
    '(?:/p/|/dp/|/product/|/item/|[?&]pid=|/blog/|/news/|/press/|/\\d{4}/\\d{2}/)',
  person_label_pattern: '^(?:dr|mr|mrs|ms|prof)\\.?\\s',
  max_page_chars: 6000,
  max_total_chars: 12000,
  min_words: 40,
  cache_seconds: 300,
  negative_cache_seconds: 1,
  cache_max_entries: 256,
  content_types: ['application/xhtml+xml', 'text/html'],
  version: 'brand-evidence-v1',
  failure_messages: {
    no_usable_website_url:
      "No usable website URL was supplied, so there is no brand content to work from. Add the brand's website URL, or describe the brand manually.",
    website_unreachable:
      "The brand's website could not be read (unreachable, blocked, or empty). Check the website URL, or describe the brand manually.",
    insufficient_website_content:
      "The brand's website returned too little readable text to work from — often a site that renders its content with JavaScript. Describe the brand manually instead.",
    evidence_fetch_timeout:
      "Reading the brand's website timed out. Try again, or describe the brand manually.",
    evidence_fetch_failed:
      "Reading the brand's website failed unexpectedly. Try again, or describe the brand manually.",
  },
};
