/** Native earned-actions catalog: deterministic decisions over persisted evidence. */
export const earnedActions = {
  ACTION_PATH_OWNED: 'owned',
  ACTION_PATH_EARNED: 'earned',
  ACTION_PATHS: ['earned', 'owned'],
  SOURCE_ROLLUP_MAX_DOMAINS: 100,
  SOURCE_ROLLUP_MAX_URLS: 6,
  SOURCE_ROLLUP_MAX_PROMPTS: 12,
  RULE_EARNED_SOURCE_RECURS: 'earned_source_recurs_beside_gap',
  EARNED_SOURCE_MIN_ANSWERS: 2,
  EARNED_SOURCE_MIN_USAGE_RATE: 0.1,
  EARNED_USAGE_FACTOR_MAX: 2,
  EARNED_COMPETITOR_FACTOR_MAX: 1.5,
  EARNED_COMPETITOR_FACTOR_STEP: 0.1,
  EARNED_SOURCE_DEFAULT_ROLE: 'Marketing',
  EARNED_SOURCE_DEFAULT_SKILL: 'article',
  EARNED_SUGGESTED_SKILL_BY_CLASS: {
    review_marketplace: 'comparison',
    editorial_third_party: 'article',
    community: 'reddit',
    social: 'linkedin',
    institutional: 'article',
    video: 'youtube',
  },
  EARNED_SUGGESTED_ROLE_BY_CLASS: {
    review_marketplace: 'Marketing',
    editorial_third_party: 'PR',
    community: 'Founder',
    social: 'Marketing',
    institutional: 'PR',
    video: 'Marketing',
  },
  RULE_EARNED_PAGE_ACQUIRE: 'earned_page_acquire_listing',
  RULE_EARNED_PAGE_CORRECT: 'earned_page_correct_listing',
  RULE_EARNED_PAGE_DEFEND: 'earned_page_defend_listing',
  RULE_EARNED_PAGE_RESEARCH: 'earned_page_research_source',
  EARNED_PAGE_RULE_IDS: [
    'earned_page_acquire_listing',
    'earned_page_correct_listing',
    'earned_page_defend_listing',
    'earned_page_research_source',
  ],
  EARNED_PAGE_TARGET_PREFIX: 'earned-page:',
  DISCREPANCY_NOT_LISTED_AS_ENTRY: 'not_listed_as_entry',
  DISCREPANCY_OWNED_DOMAIN_MISSING: 'owned_domain_missing',
  EARNED_PAGE_INCLUDABLE_FORMATS: ['comparison', 'directory', 'listicle', 'review'],
  EARNED_PAGE_MIN_RECURRENCE: 2,
  EARNED_PAGE_RESEARCH_MIN_RECURRENCE: 3,
  EARNED_PAGE_USAGE_FACTOR_MAX: 2,
  EARNED_PAGE_COMPETITOR_FACTOR_MAX: 1.6,
  EARNED_PAGE_COMPETITOR_FACTOR_STEP: 0.2,
  EARNED_PAGE_SKILL_BY_FORMAT: {
    comparison: 'comparison',
    listicle: 'listicle',
    directory: 'about_us',
    review: 'case_study',
    discussion: 'reddit',
    reference: 'faq',
    article: 'article',
    video: 'youtube',
  },
  EARNED_PAGE_ROLE_BY_FORMAT: {
    comparison: 'Marketing',
    listicle: 'PR',
    directory: 'Marketing',
    review: 'PR',
    discussion: 'Founder',
    reference: 'Marketing',
    article: 'PR',
    video: 'Marketing',
  },
  EARNED_PAGE_DEFAULT_SKILL: 'article',
  EARNED_PAGE_DEFAULT_ROLE: 'PR',
  EARNED_PAGE_MAX_PASSAGES: 4,
  EARNED_PAGE_MAX_COMPETITORS: 12,
  EARNED_PAGE_MAX_PROMPTS: 12,
  EARNED_PAGE_DETECTOR_MAX_PAGES: 500,
};
