/** Descriptive citation taxonomy, never a causal claim or authority score.
 * Identity is resolved before third-party classification; unknown stays unknown.
 * Bump SOURCE_TAXONOMY_VERSION with classification changes.
 */
export const sourcePatterns = {
  SOURCE_ORIGIN_EXTERNAL: 'external',
  SOURCE_TAXONOMY_VERSION: 'source-taxonomy-1',
  SOURCE_MIX_PROJECTION_VERSION: 'opportunity-source-mix-1',
  CONTENT_HANDOFF_TEMPLATE_VERSION: 'opportunity-content-handoff-1',
  SOURCE_CLASS_BRAND_OWNED: 'brand_owned',
  SOURCE_CLASS_COMPETITOR_OWNED: 'competitor_owned',
  SOURCE_CLASS_COMMUNITY: 'community',
  SOURCE_CLASS_VIDEO: 'video',
  SOURCE_CLASS_SOCIAL: 'social',
  SOURCE_CLASS_INSTITUTIONAL: 'institutional',
  SOURCE_CLASS_REVIEW_MARKETPLACE: 'review_marketplace',
  SOURCE_CLASS_EDITORIAL_THIRD_PARTY: 'editorial_third_party',
  SOURCE_CLASS_OTHER_THIRD_PARTY: 'other_third_party',
  SOURCE_CLASS_SEARCH_SURFACE: 'search_surface',
  SOURCE_ORIGIN_GOOGLE_OWNED: 'google_owned',
  GOOGLE_OWNED_PLATFORM_DOMAINS: [
    'blogger.com',
    'blogspot.com',
    'goo.gl',
    'youtu.be',
    'youtube.com',
  ],
  SOURCE_CLASS_ORDER: [
    'brand_owned',
    'competitor_owned',
    'review_marketplace',
    'editorial_third_party',
    'community',
    'social',
    'institutional',
    'video',
    'search_surface',
    'other_third_party',
  ],
  COMMUNITY_DOMAINS: [
    'discourse.org',
    'news.ycombinator.com',
    'producthunt.com',
    'quora.com',
    'reddit.com',
    'slashdot.org',
    'stackexchange.com',
    'stackoverflow.com',
  ],
  VIDEO_DOMAINS: ['dailymotion.com', 'twitch.tv', 'vimeo.com', 'youtu.be', 'youtube.com'],
  SOCIAL_DOMAINS: [
    'facebook.com',
    'instagram.com',
    'linkedin.com',
    'tiktok.com',
    'twitter.com',
    'x.com',
  ],
  INSTITUTIONAL_DOMAINS: ['cdc.gov', 'europa.eu', 'gov.uk', 'nih.gov', 'who.int', 'wikipedia.org'],
  REVIEW_MARKETPLACE_DOMAINS: [
    'capterra.com',
    'clutch.co',
    'g2.com',
    'gartner.com',
    'getapp.com',
    'glassdoor.com',
    'producthunt.com',
    'softwareadvice.com',
    'sourceforge.net',
    'trustpilot.com',
    'trustradius.com',
    'yelp.com',
  ],
  EDITORIAL_DOMAINS: [
    'arstechnica.com',
    'businessinsider.com',
    'cnet.com',
    'economictimes.indiatimes.com',
    'forbes.com',
    'pcmag.com',
    'techcrunch.com',
    'techradar.com',
    'theverge.com',
    'venturebeat.com',
    'wired.com',
    'yourstory.com',
    'zdnet.com',
  ],
  SOURCE_CLASS_DOMAIN_TABLES: [
    [
      'review_marketplace',
      [
        'capterra.com',
        'clutch.co',
        'g2.com',
        'gartner.com',
        'getapp.com',
        'glassdoor.com',
        'producthunt.com',
        'softwareadvice.com',
        'sourceforge.net',
        'trustpilot.com',
        'trustradius.com',
        'yelp.com',
      ],
    ],
    ['institutional', ['cdc.gov', 'europa.eu', 'gov.uk', 'nih.gov', 'who.int', 'wikipedia.org']],
    [
      'social',
      ['facebook.com', 'instagram.com', 'linkedin.com', 'tiktok.com', 'twitter.com', 'x.com'],
    ],
    ['video', ['dailymotion.com', 'twitch.tv', 'vimeo.com', 'youtu.be', 'youtube.com']],
    [
      'community',
      [
        'discourse.org',
        'news.ycombinator.com',
        'producthunt.com',
        'quora.com',
        'reddit.com',
        'slashdot.org',
        'stackexchange.com',
        'stackoverflow.com',
      ],
    ],
    [
      'editorial_third_party',
      [
        'arstechnica.com',
        'businessinsider.com',
        'cnet.com',
        'economictimes.indiatimes.com',
        'forbes.com',
        'pcmag.com',
        'techcrunch.com',
        'techradar.com',
        'theverge.com',
        'venturebeat.com',
        'wired.com',
        'yourstory.com',
        'zdnet.com',
      ],
    ],
  ],
  PATTERN_COMPETITOR_OWNED_SOURCES: 'competitor_owned_sources_cited',
  PATTERN_INDEPENDENT_VALIDATION: 'independent_validation_present',
  PATTERN_COMMUNITY_EVIDENCE: 'community_evidence_present',
  PATTERN_VIDEO_EVIDENCE: 'video_evidence_present',
  PATTERN_MULTIPLE_INDEPENDENT_DOMAINS: 'multiple_independent_domains',
  MULTIPLE_INDEPENDENT_DOMAIN_MIN: 3,
  MAX_TOP_CITATIONS: 6,
  ACTION_STRENGTHEN_OWNED_ANSWER: 'strengthen_owned_answer_page',
  ACTION_PURSUE_INDEPENDENT_EVIDENCE: 'pursue_independent_evidence',
  ACTION_PURSUE_COMMUNITY_EVIDENCE: 'pursue_community_evidence',
  ACTION_INVESTIGATE_COMPETITOR_SOURCES: 'investigate_competitor_sources',
  ACTION_DEFAULT: 'strengthen_owned_answer_page',
  PATTERN_TO_ACTION: [
    ['multiple_independent_domains', 'pursue_independent_evidence'],
    ['competitor_owned_sources_cited', 'investigate_competitor_sources'],
    ['independent_validation_present', 'pursue_independent_evidence'],
    ['community_evidence_present', 'pursue_community_evidence'],
    ['video_evidence_present', 'pursue_community_evidence'],
  ],
  _PUBLIC_SECOND_LEVEL_LABELS: ['ac', 'co', 'com', 'edu', 'gov', 'net', 'org'],
};
