/** Bounded publisher-page inspection. Page lifecycle is separate from presence:
 * an unread page never establishes absence. Page format never classifies a publisher.
 */
export const sourcePages = {
  identity_version: 'citation-identity-1',
  inspector_version: 'source-page-inspector-1',
  extractor_version: 'source-page-extractor-2',
  presence_version: 'source-page-presence-1',
  format_version: 'source-page-format-1',
  passage_chars: 300,
  max_passages: 8,
  max_text_chars: 400000,
  max_headings: 24,
  max_outbound_domains: 64,
  max_structured_types: 16,
  title_max_chars: 500,
  min_coverage_chars: 600,
  request_timeout_seconds: 15,
  hop_timeout_seconds: 30,
  max_redirects: 5,
  max_wire_bytes: 3000000,
  max_decoded_bytes: 10000000,
  per_host_delay_seconds: 1,
  fetch_concurrency: 4,
  allowed_content_types: ['text/html', 'application/xhtml+xml'],
  budget_window_hours: 24,
  budget_per_window: 120,
  batch_max: 25,
  stale_after_hours: 336,
  max_redirects_per_domain: 3,
  claim_lease_minutes: 30,
  reuse_within_hours: 12,
  schema_formats: [
    ['discussionforumposting', 'discussion'],
    ['qapage', 'discussion'],
    ['videoobject', 'video'],
    ['itemlist', 'listicle'],
    ['faqpage', 'reference'],
    ['newsarticle', 'article'],
    ['blogposting', 'article'],
    ['article', 'article'],
  ],
  heading_formats: [
    [String.raw`\bvs\.?\b|\bversus\b|\bcompared?\s+to\b`, 'comparison'],
    [String.raw`\balternatives?\b|\bcompetitors?\b`, 'comparison'],
    [String.raw`\bbest\b|\btop\s+\d+\b|\b\d+\s+best\b`, 'listicle'],
    [String.raw`\breviews?\b|\bhands[- ]on\b`, 'review'],
    [String.raw`\bdirectory\b|\bprofile\b|\blistings?\b`, 'directory'],
    [String.raw`\bforum\b|\bthread\b|\bdiscussion\b`, 'discussion'],
  ],
  schema_max_depth: 12,
  min_alias_chars: 3,
  redirect_hosts: ['vertexaisearch.cloud.google.com', 'grounding-api-redirect'],
  kind_formats: {
    homepage: 'homepage',
    comparison: 'comparison',
    alternative: 'alternative',
    listicle: 'listicle',
    how_to: 'how_to',
    guide: 'how_to',
    article: 'article',
    case_study_review: 'review',
    category: 'category',
    product: 'product',
    pricing: 'product',
    service: 'product',
    docs: 'reference',
    faq: 'reference',
    local: 'profile',
    about_contact: 'profile',
  },
  url_formats: [
    [
      '(^|-)(forum|forums|thread|threads|discussion|discussions|comments|questions|answers)(-|$)|(^|-)r-[a-z0-9_]+(-|$)',
      'discussion',
    ],
    [
      '(^|-)(profile|profiles|vendor|vendors|listing|listings|directory|supplier|suppliers)(-|$)',
      'profile',
    ],
  ],
  format_method_strength: ['structured_data', 'heading_evidence', 'url_pattern', 'none'],
};

export const sourcePageVocabulary = {
  INSPECTION_QUEUED: 'queued',
  INSPECTION_INSPECTED: 'inspected',
  INSPECTION_BLOCKED: 'blocked',
  INSPECTION_FAILED: 'failed',
  INSPECTION_STALE: 'stale',
  INSPECTION_REASON_ROBOTS: 'robots_disallowed',
  INSPECTION_REASON_ROBOTS_UNAVAILABLE: 'robots_unavailable',
  INSPECTION_REASON_NON_HTML: 'non_html',
  INSPECTION_REASON_STATUS: 'status_rejected',
  INSPECTION_REASON_TRANSPORT: 'transport_error',
  INSPECTION_REASON_UNRESOLVED_REDIRECT: 'unresolved_redirect',
  PAGE_FORMAT_COMPARISON: 'comparison',
  PAGE_FORMAT_LISTICLE: 'listicle',
  PAGE_FORMAT_REVIEW: 'review',
  PAGE_FORMAT_DIRECTORY: 'directory',
  PAGE_FORMAT_DISCUSSION: 'discussion',
  PAGE_FORMAT_REFERENCE: 'reference',
  PAGE_FORMAT_ARTICLE: 'article',
  PAGE_FORMAT_VIDEO: 'video',
  PAGE_FORMAT_HOMEPAGE: 'homepage',
  PAGE_FORMAT_CATEGORY: 'category',
  PAGE_FORMAT_PRODUCT: 'product',
  PAGE_FORMAT_PROFILE: 'profile',
  PAGE_FORMAT_ALTERNATIVE: 'alternative',
  PAGE_FORMAT_HOW_TO: 'how_to',
  PAGE_FORMAT_METHOD_STRUCTURED_DATA: 'structured_data',
  PAGE_FORMAT_METHOD_HEADING_EVIDENCE: 'heading_evidence',
  PAGE_FORMAT_METHOD_URL_PATTERN: 'url_pattern',
  PAGE_FORMAT_METHOD_NONE: 'none',
  PRESENCE_PRESENT: 'present',
  PRESENCE_NOT_DETECTED: 'not_detected',
  PRESENCE_AMBIGUOUS: 'ambiguous',
  PRESENCE_PARTIAL: 'partial',
  PRESENCE_MATCH_EXACT_ALIAS: 'exact_alias',
  PRESENCE_MATCH_NORMALIZED_ALIAS: 'normalized_alias',
  PRESENCE_MATCH_NONE: 'none',
  ENTITY_KIND_BRAND: 'brand',
  ENTITY_KIND_COMPETITOR: 'competitor',
  SOURCE_PAGE_INSPECTOR_VERSION: sourcePages.inspector_version,
  SOURCE_PAGE_PRESENCE_VERSION: sourcePages.presence_version,
  SOURCE_PAGE_FORMAT_VERSION: sourcePages.format_version,
  SOURCE_PAGE_MIN_COVERAGE_CHARS: sourcePages.min_coverage_chars,
  PAGE_FORMAT_METHOD_STRENGTH: sourcePages.format_method_strength,
};

export const urlIdentity = {
  version: sourcePages.identity_version,
  verbatim: 'verbatim',
  unresolved: 'unresolved',
};
